spring:
  application:
    name: cronai-gen-ms
  mongodb:
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    host: ${MONGO_HOST}
    database: gen

server:
  servlet:
    context-path: /svc

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true