spring:
  application:
    name: cronai-gen-ms
  mongodb:
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    host: ${MONGO_HOST}
    database: gen
    representation:
      uuid: standard


server:
  servlet:
    context-path: /svc

jobrunr:
  background-job-server:
    enabled: true
  dashboard:
    enabled: true
    port: 8000


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true